import {VisualizationState,prepareItems,prepareTableRows,tableCSV,tableRowHeight,tableFontSize,zoomRowHeight,zoomLabelSize,normalizeSearch,formatPercent} from './core/visualization.js';

const $=s=>document.querySelector(s);
const make=(tag,text,cls)=>{const node=document.createElement(tag);if(text!==undefined)node.textContent=text;if(cls)node.className=cls;return node};
function markedLabel(text,query,cls='viz-label'){const span=make('span',undefined,cls),term=normalizeSearch(query),source=normalizeSearch(text),at=term?source.indexOf(term):-1;if(at<0){span.textContent=text;return span}span.append(document.createTextNode(text.slice(0,at)),make('mark',text.slice(at,at+query.length)),document.createTextNode(text.slice(at+query.length)));return span}
function safeName(value){return String(value||'資料表格').replace(/[\\/:*?"<>|\s]+/g,'-').replace(/^-+|-+$/g,'')||'資料表格'}

export class Visualization{
 constructor({getContext,onClose}){
  this.getContext=getContext;this.onClose=onClose;this.state=new VisualizationState();this.context=null;this.pushed=false;
  this.view=$('#visualization-view');this.analysis=$('#analysis-view');this.chart=$('#viz-chart');this.tabs=[...document.querySelectorAll('.viz-tabs [data-view]')];
  $('#viz-back').onclick=()=>this.close();$('#viz-search').oninput=e=>{this.state.search=e.target.value;this.render('search')};$('#viz-clear-search').onclick=()=>{this.state.search='';$('#viz-search').value='';this.render('search');$('#viz-search').focus()};$('#viz-sort').onchange=e=>{this.state.sort=e.target.value;this.render('sort')};$('#viz-palette').onchange=e=>{this.state.palette=e.target.value;this.render('palette')};$('#viz-zoom').oninput=e=>{this.state.zoom[this.state.view]=Number(e.target.value);this.applyZoom()};$('#viz-export').onclick=()=>this.exportCSV();
  for(const tab of this.tabs){tab.onclick=()=>this.selectView(tab.dataset.view);tab.onkeydown=e=>{if(!['ArrowLeft','ArrowRight'].includes(e.key))return;e.preventDefault();const offset=e.key==='ArrowRight'?1:-1,index=this.tabs.indexOf(tab),next=this.tabs[(index+offset+this.tabs.length)%this.tabs.length];this.selectView(next.dataset.view);next.focus()}}
  this.labelResizeObserver=new ResizeObserver(()=>this.fitLabels());this.labelResizeObserver.observe(this.chart);
  addEventListener('popstate',()=>{if(this.opened&&!location.hash.includes('visualization'))this.close(false)});
 }
 open(){
  this.context=this.getContext();this.state.setSource(this.context.key,this.context.sort);this.opened=true;this.analysis.hidden=true;this.view.hidden=false;$('#viz-source').replaceChildren(make('span','分析標的','viz-source-label'),make('strong',`${this.context.type}：${this.context.name}`));$('#viz-search').value=this.state.search;$('#viz-sort').value=this.state.sort;$('#viz-palette').value=this.state.palette;this.updateTabs();if(!location.hash.includes('visualization')){history.pushState({view:'visualization'},'',location.pathname+location.search+'#visualization');this.pushed=true}this.render('open');this.chart.scrollTop=0;$('#viz-back').focus();
 }
 close(navigate=true){if(!this.opened)return;this.opened=false;this.view.hidden=true;this.analysis.hidden=false;if(navigate&&this.pushed&&location.hash.includes('visualization')){this.pushed=false;history.back()}else if(navigate&&location.hash.includes('visualization'))history.replaceState({},'',location.pathname+location.search);this.onClose?.()}
 selectView(view){if(!['bar','table'].includes(view)||view===this.state.view)return;this.state.view=view;this.updateTabs();this.render('view');this.chart.scrollTop=0}
 updateTabs(){for(const tab of this.tabs){const selected=tab.dataset.view===this.state.view;tab.setAttribute('aria-selected',String(selected));tab.tabIndex=selected?0:-1}$('#viz-export').hidden=this.state.view!=='table';$('#viz-zoom').value=String(this.state.zoom[this.state.view]);this.chart.classList.toggle('is-table',this.state.view==='table')}
 applyZoom(){if(this.state.view==='table')this.applyTableZoom();else {this.applyBarZoom();this.fitLabels()}}
 fitLabels(){cancelAnimationFrame(this.labelFrame);this.labelFrame=requestAnimationFrame(()=>{if(!this.opened||this.state.view!=='bar')return;const labels=[...this.chart.querySelectorAll('.viz-label')];for(const label of labels)label.classList.remove('is-wrapped');if(this.state.zoom.bar<40)return;const size=Math.max(12,Math.min(zoomLabelSize(this.state.zoom.bar)*.85,(zoomRowHeight(this.state.zoom.bar)-4)/2.3));this.chart.style.setProperty('--viz-wrapped-size',size+'px');const overflowing=labels.filter(label=>label.scrollWidth>label.clientWidth+1);for(const label of overflowing){label.classList.add('is-wrapped');label.title=label.textContent}})}
 applyBarZoom(){const oldHeight=Number.parseFloat(getComputedStyle(this.chart).getPropertyValue('--viz-row-height'))||48,center=(this.chart.scrollTop+this.chart.clientHeight/2)/oldHeight,height=zoomRowHeight(this.state.zoom.bar);this.chart.style.setProperty('--viz-row-height',height+'px');this.chart.style.setProperty('--viz-label-size',zoomLabelSize(this.state.zoom.bar)+'px');this.chart.classList.toggle('viz-dense',this.state.zoom.bar<40);$('#viz-zoom-value').value=this.state.zoom.bar+'%';this.chart.scrollTop=Math.max(0,center*height-this.chart.clientHeight/2)}
 applyTableZoom(){const oldHeight=Number.parseFloat(getComputedStyle(this.chart).getPropertyValue('--viz-table-row-height'))||51,center=(this.chart.scrollTop+this.chart.clientHeight/2)/oldHeight,height=tableRowHeight(this.state.zoom.table);this.chart.style.setProperty('--viz-table-row-height',height+'px');this.chart.style.setProperty('--viz-table-font-size',tableFontSize(this.state.zoom.table)+'px');$('#viz-zoom-value').value=this.state.zoom.table+'%';this.chart.scrollTop=Math.max(0,center*height-this.chart.clientHeight/2)}
 render(reason){
  const items=prepareItems(this.context.items,this.state.search,this.state.sort),matches=items.filter(x=>x.matched);this.chart.dataset.palette=this.state.palette;$('#viz-clear-search').disabled=!this.state.search;$('#viz-status').textContent=this.state.view==='table'?`符合 ${matches.length}／全部 ${items.length} 項 · 分析母集合 ${this.context.documentTotal} 筆 · 各類別可能包含相同文件，累積比例可能超過 100%`:`符合 ${matches.length}／全部 ${items.length} 項 · 文件數`;
  this.selection(items);this.chart.replaceChildren();this.updateTabs();
  if(!items.length){this.chart.append(make('p','此條件下沒有可視覺化項目','viz-empty'));return}
  if(this.state.view==='table')this.renderTable(items);else this.renderBars(items);
  this.applyZoom();
  if(reason==='search'&&matches.length)this.chart.querySelector(`[data-value=${CSS.escape(matches[0].value)}]`)?.scrollIntoView({block:'nearest'});
 }
 renderBars(items){
  const max=Math.max(1,...items.map(x=>x.count)),top=new Set(prepareItems(this.context.items,'','count-desc').slice(0,3).map(x=>x.value));
  for(const item of items){const row=make('button',undefined,'viz-bar-row');row.type='button';this.decorateRow(row,item,top);const track=make('span',undefined,'viz-bar-track'),bar=make('span',undefined,'viz-bar'),count=make('span',String(item.count),'viz-count');bar.style.width=`calc((100% - 54px) * ${item.count/max})`;bar.title=`${item.label}：${item.count}筆`;bar.setAttribute('aria-label',bar.title);track.append(bar,count);row.append(markedLabel(item.label,item.matched?this.state.search:''),track);this.bindSelection(row,item);this.chart.append(row)}
  this.chart.setAttribute('aria-label',`${this.context.type}${this.context.name}水平長條圖，符合${items.filter(x=>x.matched).length}項，共${items.length}項`)
 }
 renderTable(items){
  const rows=prepareTableRows(items,this.context.documentTotal),top=new Set(prepareItems(this.context.items,'','count-desc').slice(0,3).map(x=>x.value)),table=make('table',undefined,'viz-data-table'),caption=make('caption',`${this.context.type}：${this.context.name}；分析母集 ${this.context.documentTotal} 筆文件`),head=make('thead'),headRow=make('tr'),body=make('tbody');
  for(const title of ['序號','類別名稱','文件數','比例','累積比例']){const th=make('th',title);th.scope='col';headRow.append(th)}head.append(headRow);
  for(const item of rows){const row=make('tr');row.tabIndex=0;row.setAttribute('role','button');this.decorateRow(row,item,top);const ratio=make('div',undefined,'viz-ratio'),meter=make('span',undefined,'viz-ratio-track'),fill=make('span',undefined,'viz-ratio-fill');fill.style.width=`${Math.max(0,Math.min(100,item.proportion||0))}%`;meter.append(fill);ratio.append(meter,make('span',formatPercent(item.proportion)));const name=make('td');name.append(markedLabel(item.label,item.matched?this.state.search:'','viz-table-label'));for(const cell of [make('td',String(item.rank)),name,make('td',String(item.count)),make('td'),make('td',formatPercent(item.cumulative))])row.append(cell);row.children[3].append(ratio);this.bindSelection(row,item);body.append(row)}
  table.append(caption,head,body);this.chart.append(table);this.chart.setAttribute('aria-label',`${this.context.type}${this.context.name}資料表格，符合${items.filter(x=>x.matched).length}項，共${items.length}項，分析母集${this.context.documentTotal}筆文件`)
 }
 decorateRow(row,item,top){row.dataset.value=item.value;row.classList.toggle('is-top-three',top.has(item.value));row.classList.toggle('is-unmatched',!item.matched);row.classList.toggle('is-selected',this.state.selected.has(item.value));row.setAttribute('aria-pressed',String(this.state.selected.has(item.value)));row.setAttribute('aria-label',`${item.label}，${item.count}筆${item.matched?'，符合搜尋':'，不符合搜尋'}${this.state.selected.has(item.value)?'，已標示':''}`)}
 bindSelection(row,item){row.onclick=()=>{this.state.toggle(item.value);this.render('selection')};row.onkeydown=e=>{if(!['Enter',' '].includes(e.key))return;e.preventDefault();row.click()};row.onfocus=()=>{$('#viz-focus-detail').textContent=`${item.label} · ${item.count}筆${this.state.selected.has(item.value)?' · 已標示':''}`}}
 selection(items){const box=$('#viz-selection');box.replaceChildren();box.hidden=!this.state.selected.size;if(box.hidden)return;const names=new Map(items.map(x=>[x.value,x.label]));for(const value of this.state.selected){const b=make('button',(names.get(value)||value)+' ×');b.type='button';b.onclick=()=>{this.state.toggle(value);this.render('selection')};box.append(b)}const clear=make('button',`清除 ${this.state.selected.size} 項`,'viz-clear-selection');clear.type='button';clear.onclick=()=>{this.state.clearSelection();this.render('selection')};box.append(clear)}
 exportCSV(){const items=prepareItems(this.context.items,this.state.search,this.state.sort),rows=prepareTableRows(items,this.context.documentTotal),blob=new Blob([tableCSV(rows)],{type:'text/csv;charset=utf-8'}),url=URL.createObjectURL(blob),link=make('a');link.href=url;link.download=`${safeName(this.context.name)}-${safeName(this.context.version)}.csv`;document.body.append(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(url),0)}
}
