import {VisualizationState,prepareItems,zoomRowHeight,zoomLabelSize,normalizeSearch} from './core/visualization.js';

const $=s=>document.querySelector(s);
const make=(tag,text,cls)=>{const node=document.createElement(tag);if(text!==undefined)node.textContent=text;if(cls)node.className=cls;return node};
function markedLabel(text,query){const span=make('span',undefined,'viz-label'),term=normalizeSearch(query),source=normalizeSearch(text),at=term?source.indexOf(term):-1;if(at<0){span.textContent=text;return span}span.append(document.createTextNode(text.slice(0,at)),make('mark',text.slice(at,at+query.length)),document.createTextNode(text.slice(at+query.length)));return span}

export class Visualization{
 constructor({getContext,onClose}){
  this.getContext=getContext;this.onClose=onClose;this.state=new VisualizationState();this.context=null;this.pushed=false;
  this.view=$('#visualization-view');this.analysis=$('#analysis-view');this.chart=$('#viz-chart');
  $('#viz-back').onclick=()=>this.close();$('#viz-search').oninput=e=>{this.state.search=e.target.value;this.render('search')};$('#viz-clear-search').onclick=()=>{this.state.search='';$('#viz-search').value='';this.render('search');$('#viz-search').focus()};$('#viz-sort').onchange=e=>{this.state.sort=e.target.value;this.render('sort')};$('#viz-palette').onchange=e=>{this.state.palette=e.target.value;this.render('palette')};$('#viz-zoom').oninput=e=>{this.state.zoom.bar=Number(e.target.value);this.applyZoom()};
  addEventListener('popstate',()=>{if(this.opened&&!location.hash.includes('visualization'))this.close(false)});
 }
 open(){
  this.context=this.getContext();this.state.setSource(this.context.key,this.context.sort);this.opened=true;this.analysis.hidden=true;this.view.hidden=false;$('#viz-source').replaceChildren(make('span','分析標的','viz-source-label'),make('strong',`${this.context.type}：${this.context.name}`));$('#viz-search').value=this.state.search;$('#viz-sort').value=this.state.sort;$('#viz-palette').value=this.state.palette;$('#viz-zoom').value=String(this.state.zoom.bar);if(!location.hash.includes('visualization')){history.pushState({view:'visualization'},'',location.pathname+location.search+'#visualization');this.pushed=true}this.render('open');this.chart.scrollTop=0;$('#viz-back').focus();
 }
 close(navigate=true){if(!this.opened)return;this.opened=false;this.view.hidden=true;this.analysis.hidden=false;if(navigate&&this.pushed&&location.hash.includes('visualization')){this.pushed=false;history.back()}else if(navigate&&location.hash.includes('visualization'))history.replaceState({},'',location.pathname+location.search);this.onClose?.()}
 applyZoom(){const oldHeight=Number.parseFloat(getComputedStyle(this.chart).getPropertyValue('--viz-row-height'))||48,center=(this.chart.scrollTop+this.chart.clientHeight/2)/oldHeight,height=zoomRowHeight(this.state.zoom.bar);this.chart.style.setProperty('--viz-row-height',height+'px');this.chart.style.setProperty('--viz-label-size',zoomLabelSize(this.state.zoom.bar)+'px');this.chart.classList.toggle('viz-dense',this.state.zoom.bar<40);$('#viz-zoom-value').value=this.state.zoom.bar+'%';this.chart.scrollTop=Math.max(0,center*height-this.chart.clientHeight/2)}
 render(reason){
  const items=prepareItems(this.context.items,this.state.search,this.state.sort),matches=items.filter(x=>x.matched),max=Math.max(1,...items.map(x=>x.count)),top=new Set(prepareItems(this.context.items,'','count-desc').slice(0,3).map(x=>x.value)),height=zoomRowHeight(this.state.zoom.bar);
  this.chart.style.setProperty('--viz-row-height',height+'px');this.chart.style.setProperty('--viz-label-size',zoomLabelSize(this.state.zoom.bar)+'px');this.chart.dataset.palette=this.state.palette;this.chart.classList.toggle('viz-dense',this.state.zoom.bar<40);$('#viz-zoom-value').value=this.state.zoom.bar+'%';$('#viz-clear-search').disabled=!this.state.search;$('#viz-status').textContent=`符合 ${matches.length}／全部 ${items.length} 項 · 文件數`;
  this.selection(items);this.chart.replaceChildren();
  if(!items.length){this.chart.append(make('p','此條件下沒有可視覺化項目','viz-empty'));return}
  for(const item of items){const row=make('button',undefined,'viz-bar-row');row.type='button';row.dataset.value=item.value;row.classList.toggle('is-top-three',top.has(item.value));row.classList.toggle('is-unmatched',!item.matched);row.classList.toggle('is-selected',this.state.selected.has(item.value));row.setAttribute('aria-pressed',String(this.state.selected.has(item.value)));row.setAttribute('aria-label',`${item.label}，${item.count}筆${item.matched?'，符合搜尋':'，不符合搜尋'}${this.state.selected.has(item.value)?'，已標示':''}`);const track=make('span',undefined,'viz-bar-track'),bar=make('span',undefined,'viz-bar'),count=make('span',String(item.count),'viz-count');bar.style.width=`calc((100% - 54px) * ${item.count/max})`;bar.title=`${item.label}：${item.count}筆`;bar.setAttribute('aria-label',bar.title);track.append(bar,count);row.append(markedLabel(item.label,item.matched?this.state.search:''),track);row.onclick=()=>{this.state.toggle(item.value);this.render('selection')};row.onfocus=()=>{$('#viz-focus-detail').textContent=`${item.label} · ${item.count}筆${this.state.selected.has(item.value)?' · 已標示':''}`};this.chart.append(row)}
  if(reason==='search'&&matches.length)[...this.chart.children].find(row=>row.dataset.value===matches[0].value)?.scrollIntoView({block:'nearest'});
  this.chart.setAttribute('aria-label',`${this.context.type}${this.context.name}水平長條圖，符合${matches.length}項，共${items.length}項，依${this.state.sort==='title-asc'?'標籤升冪':'文件數降冪'}排列`);
 }
 selection(items){const box=$('#viz-selection');box.replaceChildren();box.hidden=!this.state.selected.size;if(box.hidden)return;const names=new Map(items.map(x=>[x.value,x.label]));for(const value of this.state.selected){const b=make('button',(names.get(value)||value)+' ×');b.type='button';b.onclick=()=>{this.state.toggle(value);this.render('selection')};box.append(b)}const clear=make('button',`清除 ${this.state.selected.size} 項`,'viz-clear-selection');clear.type='button';clear.onclick=()=>{this.state.clearSelection();this.render('selection')};box.append(clear)}
}
